<?php
// 代码生成时间: 2025-09-19 06:12:04
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

/**
 * 一个简单的Excel表格自动生成器
 *
 * 这个程序使用PhpSpreadsheet库来创建Excel文件。
 * 它提供了创建空白表格和填充数据的基本功能。
 */
class ExcelGenerator {

    /**
     * 创建一个新的Excel工作簿
     *
     * @param string $filename 文件名
     * @return Spreadsheet
     */
    public function createSpreadsheet(string $filename): Spreadsheet {
        // 创建一个新的Spreadsheet实例
        $spreadsheet = new Spreadsheet();

        // 创建一个新的工作表
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Sheet1');

        // 设置文件名
        $spreadsheet->getProperties()
            ->setCreator('Excel Generator')
            ->setLastModifiedBy('Excel Generator')
            ->setTitle('Office 2007 XLSX Document')
            ->setSubject('Office 2007 XLSX Document')
            ->setDescription('Document generated by PhpSpreadsheet', '')
            ->setKeywords('office 2007 openxml php')
            ->setCategory('');

        return $spreadsheet;
    }

    /**
     * 向Excel工作簿添加数据
     *
     * @param Spreadsheet $spreadsheet Spreadsheet实例
     * @param array $data 要添加的数据
     * @return void
     */
    public function addDataToSheet(Spreadsheet $spreadsheet, array $data): void {
        // 获取活动工作表
        $sheet = $spreadsheet->getActiveSheet();

        // 从第一行开始填充数据
        $row = 1;
        foreach ($data as $rowData) {
            $column = 1; // 从A列开始
            foreach ($rowData as $cellValue) {
                $sheet->setCellValueByColumnAndRow($column, $row, $cellValue);
                $column++;
            }
            $row++;
        }
    }

    /**
     * 保存Excel工作簿到文件
     *
     * @param Spreadsheet $spreadsheet Spreadsheet实例
     * @param string $filename 文件名
     * @return void
     */
    public function saveSpreadsheet(Spreadsheet $spreadsheet, string $filename): void {
        // 创建一个XlsxWriter实例来保存文件
        $writer = new Xlsx($spreadsheet);

        // 保存文件到指定路径
        try {
            $writer->save($filename);
        } catch (Exception $e) {
            // 错误处理
            echo 'Error: ' . $e->getMessage();
            exit;
        }
    }
}

// 使用示例
try {
    $generator = new ExcelGenerator();
    $spreadsheet = $generator->createSpreadsheet('example.xlsx');
    $generator->addDataToSheet($spreadsheet, [
        ['Name', 'Age', 'City'],
        ['John', 30, 'New York'],
        ['Jane', 25, 'Los Angeles'],
    ]);
    $generator->saveSpreadsheet($spreadsheet, 'example.xlsx');
    echo 'Excel file generated successfully!';
} catch (Exception $e) {
    // 错误处理
    echo 'Error: ' . $e->getMessage();
}